using System.Text.Json;
using FieldLog.Data;
using FieldLog.Models;
using FieldLog.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FieldLog.Pages.Logs;

[Authorize]
public class EditModel : PageModel
{
    private readonly AppDbContext _db;
    private readonly UserManager<AppUser> _userManager;
    private readonly IWebHostEnvironment _env;

    public EditModel(AppDbContext db, UserManager<AppUser> userManager, IWebHostEnvironment env)
    {
        _db = db;
        _userManager = userManager;
        _env = env;
    }

    [BindProperty(SupportsGet = true)]
    public Guid Id { get; set; }

    public Guid ProjectId { get; set; }
    public string ProjectName { get; set; } = "";

    [BindProperty]
    public DateOnly LogDate { get; set; }

    // JSON stored in DB (these will be auto-generated by JS into hidden inputs)
    [BindProperty] public string EventsJson { get; set; } = "[]";
    [BindProperty] public string WeatherJson { get; set; } = "{}";
    [BindProperty] public string SubcontractorsJson { get; set; } = "[]";
    [BindProperty] public string IssuesJson { get; set; } = "[]";
    [BindProperty] public string SafetyJson { get; set; } = "[]";
    [BindProperty] public string LaborJson { get; set; } = "[]";
    [BindProperty] public string EquipmentJson { get; set; } = "[]";
    [BindProperty] public string DeliveriesJson { get; set; } = "[]";
    [BindProperty] public string InspectionsJson { get; set; } = "[]";

    [BindProperty]
    public string? Notes { get; set; }

    // New photo uploads (append)
    [BindProperty]
    public List<IFormFile> Photos { get; set; } = new();

    // Existing photos for UI + delete
    public List<string> ExistingPhotoUrls { get; set; } = new();

    public async Task<IActionResult> OnGetAsync()
    {
        var userId = _userManager.GetUserId(User)!;
        var log = await Authz.GetOwnedLogAsync(_db, userId, Id);
        if (log == null) return NotFound();

        ProjectId = log.ProjectId;
        ProjectName = log.Project?.Name ?? "";

        LogDate = log.LogDate;
        Notes = log.Notes;

        // Normalize stored JSON for safe JS parsing
        EventsJson = NormalizeArrayOrEmpty(log.EventsJson);
        WeatherJson = NormalizeObjectOrEmpty(log.WeatherJson);
        SubcontractorsJson = NormalizeArrayOrEmpty(log.SubcontractorsJson);
        IssuesJson = NormalizeArrayOrEmpty(log.IssuesJson);
        SafetyJson = NormalizeArrayOrEmpty(log.SafetyJson);
        LaborJson = NormalizeArrayOrEmpty(log.LaborJson);
        EquipmentJson = NormalizeArrayOrEmpty(log.EquipmentJson);
        DeliveriesJson = NormalizeArrayOrEmpty(log.DeliveriesJson);
        InspectionsJson = NormalizeArrayOrEmpty(log.InspectionsJson);

        ExistingPhotoUrls = SafeList<string>(log.PhotoUrlsJson);

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        var userId = _userManager.GetUserId(User)!;
        var log = await Authz.GetOwnedLogAsync(_db, userId, Id);
        if (log == null) return NotFound();

        ProjectId = log.ProjectId;
        ProjectName = log.Project?.Name ?? "";

        // Re-load existing photos for redisplay if validation fails
        ExistingPhotoUrls = SafeList<string>(log.PhotoUrlsJson);

        // Validate JSON coming from hidden inputs
        try
        {
            EventsJson = NormalizeOrThrowArray(EventsJson, nameof(EventsJson));
            WeatherJson = NormalizeOrThrowObject(WeatherJson, nameof(WeatherJson));
            SubcontractorsJson = NormalizeOrThrowArray(SubcontractorsJson, nameof(SubcontractorsJson));
            IssuesJson = NormalizeOrThrowArray(IssuesJson, nameof(IssuesJson));
            SafetyJson = NormalizeOrThrowArray(SafetyJson, nameof(SafetyJson));
            LaborJson = NormalizeOrThrowArray(LaborJson, nameof(LaborJson));
            EquipmentJson = NormalizeOrThrowArray(EquipmentJson, nameof(EquipmentJson));
            DeliveriesJson = NormalizeOrThrowArray(DeliveriesJson, nameof(DeliveriesJson));
            InspectionsJson = NormalizeOrThrowArray(InspectionsJson, nameof(InspectionsJson));
        }
        catch (Exception ex)
        {
            ModelState.AddModelError(string.Empty, ex.Message);
            return Page();
        }

        // Update fields
        log.LogDate = LogDate;
        log.EventsJson = EventsJson;
        log.WeatherJson = WeatherJson;
        log.SubcontractorsJson = SubcontractorsJson;
        log.IssuesJson = IssuesJson;
        log.SafetyJson = SafetyJson;
        log.LaborJson = LaborJson;
        log.EquipmentJson = EquipmentJson;
        log.DeliveriesJson = DeliveriesJson;
        log.InspectionsJson = InspectionsJson;
        log.Notes = Notes;

        // Append newly uploaded photos
        if (Photos != null && Photos.Count > 0)
        {
            var urls = SafeList<string>(log.PhotoUrlsJson);

            var uploadsRoot = Path.Combine(_env.WebRootPath, "uploads", userId, log.ProjectId.ToString());
            Directory.CreateDirectory(uploadsRoot);

            foreach (var file in Photos.Where(f => f.Length > 0))
            {
                var ext = Path.GetExtension(file.FileName);
                if (string.IsNullOrWhiteSpace(ext)) ext = ".jpg";

                var safeName = $"{Guid.NewGuid():N}{ext}";
                var fullPath = Path.Combine(uploadsRoot, safeName);

                using var stream = System.IO.File.Create(fullPath);
                await file.CopyToAsync(stream);

                var url = $"/uploads/{userId}/{log.ProjectId}/{safeName}";
                urls.Add(url);
            }

            log.PhotoUrlsJson = JsonSerializer.Serialize(urls);
            ExistingPhotoUrls = urls;
        }

        await _db.SaveChangesAsync();
        return RedirectToPage("/Logs/View", new { id = log.Id });
    }

    // POST /Logs/Edit/{id}?handler=DeletePhoto
    public async Task<IActionResult> OnPostDeletePhotoAsync(Guid id, string photoUrl)
    {
        var userId = _userManager.GetUserId(User)!;
        var log = await Authz.GetOwnedLogAsync(_db, userId, id);
        if (log == null) return NotFound();

        var urls = SafeList<string>(log.PhotoUrlsJson);

        // Only delete if the URL belongs to this log
        if (!urls.Contains(photoUrl))
            return RedirectToPage(new { id });

        // Convert URL -> physical path
        var relative = photoUrl.TrimStart('/').Replace("/", Path.DirectorySeparatorChar.ToString());
        var physicalPath = Path.Combine(_env.WebRootPath, relative);

        // Safety: only allow deletes inside wwwroot/uploads
        var uploadsRoot = Path.Combine(_env.WebRootPath, "uploads");
        if (physicalPath.StartsWith(uploadsRoot, StringComparison.OrdinalIgnoreCase) &&
            System.IO.File.Exists(physicalPath))
        {
            System.IO.File.Delete(physicalPath);
        }

        urls.Remove(photoUrl);
        log.PhotoUrlsJson = JsonSerializer.Serialize(urls);

        await _db.SaveChangesAsync();

        return RedirectToPage(new { id });
    }

    // ---------------------------
    // JSON helpers (self-contained)
    // ---------------------------

    private static string NormalizeArrayOrEmpty(string? json)
        => NormalizeToKindOrDefault(json, JsonValueKind.Array, "[]");

    private static string NormalizeObjectOrEmpty(string? json)
        => NormalizeToKindOrDefault(json, JsonValueKind.Object, "{}");

    private static string NormalizeToKindOrDefault(string? json, JsonValueKind kind, string fallback)
    {
        if (string.IsNullOrWhiteSpace(json)) return fallback;
        try
        {
            using var doc = JsonDocument.Parse(json);
            return doc.RootElement.ValueKind == kind ? json : fallback;
        }
        catch
        {
            return fallback;
        }
    }

    private static string NormalizeOrThrowArray(string? json, string fieldName)
        => NormalizeOrThrow(json, fieldName, JsonValueKind.Array);

    private static string NormalizeOrThrowObject(string? json, string fieldName)
        => NormalizeOrThrow(json, fieldName, JsonValueKind.Object);

    private static string NormalizeOrThrow(string? json, string fieldName, JsonValueKind kind)
    {
        if (string.IsNullOrWhiteSpace(json))
            return kind == JsonValueKind.Array ? "[]" : "{}";

        try
        {
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.ValueKind != kind)
                throw new InvalidOperationException($"{fieldName} must be a JSON {(kind == JsonValueKind.Array ? "array" : "object")}.");
            return json;
        }
        catch (JsonException ex)
        {
            throw new InvalidOperationException($"{fieldName} has invalid JSON: {ex.Message}");
        }
    }

    private static List<T> SafeList<T>(string? json)
    {
        if (string.IsNullOrWhiteSpace(json)) return new List<T>();
        try { return JsonSerializer.Deserialize<List<T>>(json) ?? new List<T>(); }
        catch { return new List<T>(); }
    }
}
